package view;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.NodeStep;

public class MainFrame extends javax.swing.JFrame {

    
    private NodeStep nodeStep;
    
    public MainFrame() {
        initComponents();
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("resource/testmap.png"));
        } catch (Exception e) {}
        
        nodeStep = new NodeStep(img,
                nodeRadiusSlider.getValue(),
                nodeNumberSlider.getValue(),
                proximityPenaltySlider.getValue(),
                populationSlider.getValue(),
                crossoverRateSlider.getValue(),
                mutationRateSlider.getValue()
        );
        
        drawPanel.setEnvDisplay(nodeStep.getEnvDisplay());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        loadMapButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        populationSlider = new javax.swing.JSlider();
        generationSlider = new javax.swing.JSlider();
        crossoverRateSlider = new javax.swing.JSlider();
        mutationRateSlider = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nodeNumberSlider = new javax.swing.JSlider();
        nodeRadiusSlider = new javax.swing.JSlider();
        proximityPenaltySlider = new javax.swing.JSlider();
        oneGenButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bestRadioButton = new javax.swing.JRadioButton();
        worstRadioButton = new javax.swing.JRadioButton();
        medianRadioButton = new javax.swing.JRadioButton();
        contGenButton = new javax.swing.JButton();
        populationSizeLabel = new javax.swing.JLabel();
        generationLabel = new javax.swing.JLabel();
        crossoverLabel = new javax.swing.JLabel();
        mutationLabel = new javax.swing.JLabel();
        nodeNumberLabel = new javax.swing.JLabel();
        nodeRadiusLabel = new javax.swing.JLabel();
        proximityPenaltyLabel = new javax.swing.JLabel();
        currentGenLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bestFitnessLabel = new javax.swing.JLabel();
        drawPanel = new view.NodePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 456));

        loadMapButton.setText("Load Map");
        loadMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMapButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel1.setText("Map");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel2.setText("Genetic Algorithm");

        jLabel3.setText("Population size:");

        jLabel4.setText("Generations:");

        jLabel5.setText("Crossover rate:");

        jLabel6.setText("Mutation rate:");

        populationSlider.setMajorTickSpacing(50);
        populationSlider.setMinorTickSpacing(10);
        populationSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                populationSliderStateChanged(evt);
            }
        });
        populationSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                populationSliderMouseClicked(evt);
            }
        });

        generationSlider.setMaximum(1000);
        generationSlider.setToolTipText("");
        generationSlider.setValue(200);
        generationSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                generationSliderStateChanged(evt);
            }
        });

        crossoverRateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                crossoverRateSliderStateChanged(evt);
            }
        });

        mutationRateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mutationRateSliderStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel7.setText("Environment Variables");

        jLabel8.setText("Number of nodes:");

        jLabel9.setText("Node radius:");

        jLabel10.setText("Proximity penalty:");

        nodeNumberSlider.setMaximum(30);
        nodeNumberSlider.setValue(10);
        nodeNumberSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nodeNumberSliderStateChanged(evt);
            }
        });

        nodeRadiusSlider.setMajorTickSpacing(10);
        nodeRadiusSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nodeRadiusSliderStateChanged(evt);
            }
        });

        proximityPenaltySlider.setMaximum(200);
        proximityPenaltySlider.setToolTipText("");
        proximityPenaltySlider.setValue(10);
        proximityPenaltySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                proximityPenaltySliderStateChanged(evt);
            }
        });

        oneGenButton.setText("Run 1 Generation");
        oneGenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneGenButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel11.setText("Display");

        buttonGroup1.add(bestRadioButton);
        bestRadioButton.setSelected(true);
        bestRadioButton.setText("Best");
        bestRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(worstRadioButton);
        worstRadioButton.setText("Worst");

        buttonGroup1.add(medianRadioButton);
        medianRadioButton.setText("Median");

        contGenButton.setText("Run continous");
        contGenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contGenButtonActionPerformed(evt);
            }
        });

        populationSizeLabel.setText("50");

        generationLabel.setText("200");

        crossoverLabel.setText("0.5");

        mutationLabel.setText("0.02");

        nodeNumberLabel.setText("10");

        nodeRadiusLabel.setText("50");

        proximityPenaltyLabel.setText("10");

        currentGenLabel.setText("0");

        jLabel13.setText("Current Generation:");

        jLabel14.setText("Best Fitness:");

        bestFitnessLabel.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadMapButton)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(worstRadioButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(oneGenButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contGenButton)))
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proximityPenaltySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nodeRadiusSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nodeNumberSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(crossoverRateSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(generationSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(populationSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mutationRateSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(bestRadioButton)
                                            .addGap(49, 49, 49)
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bestFitnessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(medianRadioButton))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13)))
                                    .addGap(18, 18, 18))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(populationSizeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crossoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mutationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nodeNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nodeRadiusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proximityPenaltyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentGenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadMapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(populationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(populationSizeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(generationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(crossoverRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(crossoverLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mutationRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mutationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nodeNumberSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nodeRadiusSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeRadiusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(proximityPenaltySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proximityPenaltyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneGenButton)
                    .addComponent(contGenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(currentGenLabel)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestRadioButton)
                    .addComponent(jLabel14)
                    .addComponent(bestFitnessLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(worstRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medianRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drawPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
            .addComponent(drawPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setSlidersEnable(boolean val) {
        populationSlider.setEnabled(val);
        generationSlider.setEnabled(val);
        crossoverRateSlider.setEnabled(val);
        mutationRateSlider.setEnabled(val);
        nodeNumberSlider.setEnabled(val);
        nodeRadiusSlider.setEnabled(val);
        proximityPenaltySlider.setEnabled(val);
        
    }
    
    private void updateView() {
        int[] sol = null;
        if(bestRadioButton.isSelected()) {
            sol = nodeStep.getGA().getBest().a;
        } else if (worstRadioButton.isSelected()) {
            sol = nodeStep.getGA().getWorst().a;
        } else {
            sol = nodeStep.getGA().getMedian().a;
        }
        
        nodeStep.getEnvDisplay().setSol(sol);
        drawPanel.repaint();
        
        currentGenLabel.setText("" + nodeStep.getGA().getCurrentGeneration());
        bestFitnessLabel.setText("" + nodeStep.getGA().getBest().b);
    }
    
    private void bestRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestRadioButtonActionPerformed

    private void populationSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_populationSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_populationSliderMouseClicked

    private void loadMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMapButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("image", "jpg", "png"));
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(fileChooser.getSelectedFile().getAbsolutePath()));
                nodeStep.setMap(img);
                updateView();
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_loadMapButtonActionPerformed

    private void populationSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_populationSliderStateChanged
        nodeStep.setPopulationSize(populationSlider.getValue());
        populationSizeLabel.setText("" + populationSlider.getValue());
        
    }//GEN-LAST:event_populationSliderStateChanged

    private void generationSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_generationSliderStateChanged
        generationLabel.setText("" + generationSlider.getValue());
    }//GEN-LAST:event_generationSliderStateChanged

    private void crossoverRateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_crossoverRateSliderStateChanged
        double rate = crossoverRateSlider.getValue()/(double)crossoverRateSlider.getMaximum();
        nodeStep.setCrossoverRate(rate);
        crossoverLabel.setText("" + rate);
    }//GEN-LAST:event_crossoverRateSliderStateChanged

    private void mutationRateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mutationRateSliderStateChanged
        double rate = mutationRateSlider.getValue()/(double)mutationRateSlider.getMaximum() / 10.;
        nodeStep.setMutationRate(rate);
        mutationLabel.setText("" + rate);
    }//GEN-LAST:event_mutationRateSliderStateChanged

    private void nodeNumberSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nodeNumberSliderStateChanged
        nodeStep.setNodeNumber(nodeNumberSlider.getValue());
        nodeNumberLabel.setText("" + nodeNumberSlider.getValue());
    }//GEN-LAST:event_nodeNumberSliderStateChanged

    private void nodeRadiusSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nodeRadiusSliderStateChanged
        nodeStep.setNodeRadius(nodeRadiusSlider.getValue());
        nodeRadiusLabel.setText("" + nodeRadiusSlider.getValue());
        updateView();
    }//GEN-LAST:event_nodeRadiusSliderStateChanged

    private void proximityPenaltySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_proximityPenaltySliderStateChanged
        nodeStep.setProximityPenalty(proximityPenaltySlider.getValue());
        proximityPenaltyLabel.setText("" + proximityPenaltySlider.getValue());
    }//GEN-LAST:event_proximityPenaltySliderStateChanged

    private void oneGenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneGenButtonActionPerformed
        setSlidersEnable(false);
        for(int i = 0; i < generationSlider.getValue(); i++) {
            nodeStep.getGA().performGeneration();
        }
        updateView();
        setSlidersEnable(true);
    }//GEN-LAST:event_oneGenButtonActionPerformed
    
    private boolean runningGA = false;
    private Thread gaThread;
    private Timer timer;
    private void contGenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contGenButtonActionPerformed
        if(!runningGA) {
            setSlidersEnable(false);
            contGenButton.setText("Stop");
            timer = new Timer(10, e -> {
                for(int i = 0; i < generationSlider.getValue(); i++) {
                    nodeStep.getGA().performGeneration();
                }
                updateView();
            });
            
            /*gaThread = new Thread(() -> {
               while(timer.isRunning()) {
                   
               }
            });
            gaThread.run();*/
            timer.start();
            
        } else {
            timer.stop();
            setSlidersEnable(true);
            contGenButton.setText("Run continous");
            
        }
        runningGA = !runningGA;
        
    }//GEN-LAST:event_contGenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestFitnessLabel;
    private javax.swing.JRadioButton bestRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton contGenButton;
    private javax.swing.JLabel crossoverLabel;
    private javax.swing.JSlider crossoverRateSlider;
    private javax.swing.JLabel currentGenLabel;
    private view.NodePanel drawPanel;
    private javax.swing.JLabel generationLabel;
    private javax.swing.JSlider generationSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadMapButton;
    private javax.swing.JRadioButton medianRadioButton;
    private javax.swing.JLabel mutationLabel;
    private javax.swing.JSlider mutationRateSlider;
    private javax.swing.JLabel nodeNumberLabel;
    private javax.swing.JSlider nodeNumberSlider;
    private javax.swing.JLabel nodeRadiusLabel;
    private javax.swing.JSlider nodeRadiusSlider;
    private javax.swing.JButton oneGenButton;
    private javax.swing.JLabel populationSizeLabel;
    private javax.swing.JSlider populationSlider;
    private javax.swing.JLabel proximityPenaltyLabel;
    private javax.swing.JSlider proximityPenaltySlider;
    private javax.swing.JRadioButton worstRadioButton;
    // End of variables declaration//GEN-END:variables

}
